// Canvas storage and API state only. No native rasterizer, fonts or GPU.
const canvasCompatibilityState=(()=>{
  // Preserve the selected generated WebIDL surface while replacing its storage
  // implementation. JS implementation parameters include internal slots and
  // optional arguments, neither of which determines public WebIDL arity.
  const interfaceNames=['OffscreenCanvas','CanvasRenderingContext2D','OffscreenCanvasRenderingContext2D','ImageData','ImageBitmap','CanvasGradient','TextMetrics','HTMLCanvasElement'];
  const reflectedInterfaces=new Map(interfaceNames.map(name=>{const ctor=globalThis[name];return [name,ctor?{length:ctor.length,members:Object.getOwnPropertyDescriptors(ctor.prototype)}:null]}));
  const sourceImage=source=>{const data=host.imagePixels(elementSlot(source).nodeId);if(!data)return null;if(data.vector){host.semanticMissingAt('canvas_state.js/sourceImage','Canvas2D.vectorImageReadback',JSON.stringify({reason:'SVG image pixels require a renderer; intrinsic dimensions only are decoded'}));fail('NotSupportedError','SVG image raster readback is unsupported')}const raw=atob(data.pixels),pixels=new Uint8ClampedArray(raw.length);for(let i=0;i<raw.length;i++)pixels[i]=raw.charCodeAt(i);return {...data,pixels}};
  const imageBitmapArity=globalThis.createImageBitmap?.length;
  const selectedWorkerExposure=typeof __workerExposure==='undefined'?null:__workerExposure;
  const workerProperties=new Map((selectedWorkerExposure?.properties||[]).map(p=>[p.name,p]));
  const canvases=new WeakMap(),contexts=new WeakMap(),images=new WeakMap(),bitmaps=new WeakMap(),gradients=new WeakMap(),factories=new Map(),token={};
  const fail=(name,message)=>{throw new DOMException(message,name)};
  const uint=value=>{value=Number(value);if(!Number.isFinite(value)||value<0||value>4294967295)throw new TypeError('Canvas dimension is outside the accepted range');return Math.trunc(value)};
  const storage=(width,height)=>{if(width*height>16777216)fail('NotSupportedError','Canvas storage above 16 million pixels is not implemented');return new Uint8ClampedArray(width*height*4)};
  const defaults=()=>({fillStyle:'#000000',strokeStyle:'#000000',globalAlpha:1,globalCompositeOperation:'source-over',lineWidth:1,lineCap:'butt',lineJoin:'miter',miterLimit:10,lineDashOffset:0,shadowOffsetX:0,shadowOffsetY:0,shadowBlur:0,shadowColor:'rgba(0, 0, 0, 0)',font:'10px sans-serif',textAlign:'start',textBaseline:'alphabetic',direction:'inherit',imageSmoothingEnabled:true,imageSmoothingQuality:'low',filter:'none',fontKerning:'auto',fontStretch:'normal',fontVariantCaps:'normal',letterSpacing:'0px',wordSpacing:'0px',textRendering:'auto',transform:[1,0,0,1,0,0],dash:[]});
  const fresh=(canvas,width,height)=>{const state={canvas,width,height,context:null,kind:null,pixels:null,originClean:true,unmodeled:false,operations:[],onResize:null};canvases.set(canvas,state);return state};
  const state=canvas=>{let s=canvases.get(canvas);if(!s&&typeof HTMLCanvasElement!=='undefined'&&canvas instanceof HTMLCanvasElement)s=fresh(canvas,htmlSize(canvas,'width',300),htmlSize(canvas,'height',150));if(!s)throw new TypeError('Illegal invocation');return s};
  const buffer=s=>{if(s.readPixels)return s.readPixels();if(!s.pixels){s.pixels=storage(s.width,s.height);if(s.opaque)for(let i=3;i<s.pixels.length;i+=4)s.pixels[i]=255}materializeText(s);return s.pixels};
  const resize=(s,width,height)=>{s.width=width;s.height=height;s.originClean=true;s.pixels=null;s.operations=[];s.pendingText=[];s.unmodeled=false;s.onResize?.()};
  const htmlSize=(canvas,key,fallback)=>{const value=canvas.getAttribute(key);if(value===null||!/^\s*\d+\s*$/.test(value))return fallback;const n=Number(value);return n<=2147483647?n:fallback};
  const sync=s=>{if(typeof HTMLCanvasElement!=='undefined'&&s.canvas instanceof HTMLCanvasElement){const w=htmlSize(s.canvas,'width',300),h=htmlSize(s.canvas,'height',150);if(w!==s.width||h!==s.height)resize(s,w,h)}return s};
  const contextState=context=>{const c=contexts.get(context);if(!c)throw new TypeError('Illegal invocation');sync(c.surface);return c};
  const reportBoundary=(c,name)=>{const reported=c.reported||(c.reported=new Set());if(!reported.has(name)){reported.add(name);host.semanticMissingAt('canvas_state.js:23','Canvas2D.'+name)}};
  const record=(c,name,args)=>{reportBoundary(c,name);c.surface.unmodeled=true;c.surface.operations.push({name,args:Array.from(args,value=>typeof value==='number'||typeof value==='string'||typeof value==='boolean'||value==null?value:'[object]')});if(c.surface.operations.length>4096)c.surface.operations.shift()};
  const color=value=>{const rgba=cssColorRGBA(value);return rgba?rgba.slice(0,3).concat(Math.round(rgba[3]*255)):null};
  const normalizedColor=rgba=>rgba[3]===255?'#'+rgba.slice(0,3).map(v=>Math.round(v).toString(16).padStart(2,'0')).join(''):`rgba(${rgba[0]}, ${rgba[1]}, ${rgba[2]}, ${rgba[3]/255})`;
  class ImageData {
    constructor(data,width,height,settings={}){let pixels,w,h;if(data instanceof Uint8ClampedArray){pixels=data;w=uint(width);if(!pixels.length||pixels.length%4)fail('InvalidStateError','The input data length is not a positive multiple of four');if(!w)fail('IndexSizeError','The source width is zero');h=height===undefined?pixels.length/4/w:uint(height);if(!Number.isInteger(h)||!h||w*h*4!==pixels.length)fail('IndexSizeError','The input dimensions do not match the data')}else{w=Number(data)>>>0;h=Number(width)>>>0;if(!w||!h||Number(data)<0||Number(width)<0)fail('IndexSizeError','ImageData dimensions must be positive');pixels=storage(w,h);settings=height||{}}const space=settings.colorSpace||'srgb';if(space!=='srgb'&&space!=='display-p3')throw new TypeError('Invalid color space');if(settings.pixelFormat&&settings.pixelFormat!=='rgba-unorm8')fail('NotSupportedError','Float ImageData is not implemented');images.set(this,{data:pixels,width:w,height:h,colorSpace:space})}
    get data(){return images.get(this).data}get width(){return images.get(this).width}get height(){return images.get(this).height}get colorSpace(){return images.get(this).colorSpace}get pixelFormat(){if(!images.has(this))throw new TypeError('Illegal invocation');return'rgba-unorm8'}
  }
  class ImageBitmap {constructor(key,value){if(key!==token)throw new TypeError('Illegal constructor');bitmaps.set(this,value)}get width(){return bitmaps.get(this).width}get height(){return bitmaps.get(this).height}close(){const b=bitmaps.get(this);b.width=0;b.height=0;b.pixels=null;b.closed=true}}
  class CanvasGradient {constructor(key,kind,args){if(key!==token)throw new TypeError('Illegal constructor');gradients.set(this,{kind,args,stops:[]})}addColorStop(offset,value){offset=Number(offset);if(!Number.isFinite(offset)||offset<0||offset>1)fail('IndexSizeError','Color stop offset is outside [0, 1]');const rgba=color(String(value));if(!rgba)fail('SyntaxError','Invalid color');gradients.get(this).stops.push({offset,color:rgba})}}
  const metricSlots=new WeakMap();
  class TextMetrics {constructor(key,data){if(key!==token)throw new TypeError('Illegal constructor');metricSlots.set(this,data)}}
  const fontSize=draw=>{const match=/(\d+(?:\.\d+)?)px(?:\s|\/|$)/.exec(draw.font);return match?Number(match[1]):10};
  const glyphAdvance=draw=>fontSize(draw)*0.6+(parseFloat(draw.letterSpacing)||0);
  const alignedX=(draw,width)=>draw.textAlign==='center'?-width/2:draw.textAlign==='right'||draw.textAlign==='end'&&draw.direction!=='rtl'||draw.textAlign==='start'&&draw.direction==='rtl'?-width:0;
  const baselineShift=(draw,size)=>draw.textBaseline==='top'||draw.textBaseline==='hanging'?size*0.8:draw.textBaseline==='middle'?size*0.3:draw.textBaseline==='bottom'||draw.textBaseline==='ideographic'?-size*0.2:0;
  const textMetrics=(draw,text)=>{const size=fontSize(draw),chars=Array.from(text),advance=glyphAdvance(draw),wordSpace=parseFloat(draw.wordSpacing)||0,width=chars.length*advance+chars.filter(ch=>/\s/.test(ch)).length*wordSpace,first=chars.findIndex(ch=>!/\s/.test(ch));let last=chars.length-1;while(last>=0&&/\s/.test(chars[last]))last--;const x=alignedX(draw,width),shift=baselineShift(draw,size);return {width,actualBoundingBoxLeft:first<0?0:-(x+first*advance+chars.slice(0,first).filter(ch=>/\s/.test(ch)).length*wordSpace),actualBoundingBoxRight:first<0?0:x+last*advance+advance*0.85+chars.slice(0,last).filter(ch=>/\s/.test(ch)).length*wordSpace,fontBoundingBoxAscent:size*0.8-shift,fontBoundingBoxDescent:size*0.2+shift,actualBoundingBoxAscent:first<0?0:size*0.8-shift,actualBoundingBoxDescent:first<0?0:size*0.2+shift,emHeightAscent:size*0.8-shift,emHeightDescent:size*0.2+shift,hangingBaseline:size*0.64-shift,alphabeticBaseline:-shift,ideographicBaseline:-size*0.2-shift}};
  for(const name of Object.keys(textMetrics(defaults(),'')))Object.defineProperty(TextMetrics.prototype,name,{get(){const data=metricSlots.get(this);if(!data)throw new TypeError('Illegal invocation');return data[name]},enumerable:true,configurable:true});
  const queueText=(c,text,x,y,maxWidth,stroke)=>{x=Number(x);y=Number(y);if(!Number.isFinite(x)||!Number.isFinite(y))return;const d=c.draw,paint=paintSnapshot(stroke?d.strokeStyle:d.fillStyle);if(!paint){record(c,stroke?'strokeText':'fillText',[text,x,y,maxWidth]);return}let advance=glyphAdvance(d);const chars=Array.from(text);let wordSpace=parseFloat(d.wordSpacing)||0;const width=advance*chars.length+chars.filter(ch=>/\s/.test(ch)).length*wordSpace;if(maxWidth!==undefined){maxWidth=Number(maxWidth);if(!Number.isFinite(maxWidth)||maxWidth<=0)return;if(maxWidth<width){advance*=maxWidth/width;wordSpace*=maxWidth/width}}const actual=advance*chars.length+chars.filter(ch=>/\s/.test(ch)).length*wordSpace;x+=alignedX(d,actual);const size=fontSize(d);y+=baselineShift(d,size);
    reportBoundary(c,'approximateTextObservations');(c.surface.pendingText||(c.surface.pendingText=[])).push({chars,x,y,advance,wordSpace,size,matrix:d.transform.slice(),paint,alpha:d.globalAlpha,composite:d.globalCompositeOperation,clips:d.clipPaths||[]});c.surface.unmodeled=true;
  };
  // Lazy, coarse coverage observations, not glyph rasterization. Each codepoint
  // has one local coverage band; there are no glyph outlines or random pixels.
  const materializeText=s=>{const runs=s.pendingText;if(!runs?.length)return;s.pendingText=[];const p=s.pixels;for(const run of runs){if(run.kind==='path'){materializePath(s,run);continue}if(!supportedComposite.has(run.composite))continue;const coverage=new Uint8Array(s.width*s.height),m=run.matrix,det=m[0]*m[3]-m[1]*m[2];if(!det)continue;let cursor=run.x,left=s.width,right=0,top=s.height,bottom=0;for(const ch of run.chars){const x=cursor,y=run.y-run.size*.8,w=run.advance*.85,h=run.size;cursor+=run.advance+(/\s/.test(ch)?run.wordSpace:0);if(/\s/.test(ch))continue;const points=[[x,y],[x+w,y],[x,y+h],[x+w,y+h]].map(([a,b])=>transformPoint(m,a,b)),l=Math.max(0,Math.floor(Math.min(...points.map(p=>p[0])))),r=Math.min(s.width,Math.ceil(Math.max(...points.map(p=>p[0])))),t=Math.max(0,Math.floor(Math.min(...points.map(p=>p[1])))),b=Math.min(s.height,Math.ceil(Math.max(...points.map(p=>p[1]))));left=Math.min(left,l);right=Math.max(right,r);top=Math.min(top,t);bottom=Math.max(bottom,b);for(let yy=t;yy<b;yy++)for(let xx=l;xx<r;xx++){const px=(m[3]*(xx+.5-m[4])-m[2]*(yy+.5-m[5]))/det,py=(-m[1]*(xx+.5-m[4])+m[0]*(yy+.5-m[5]))/det;if(px>=x&&px<x+w&&py>=y&&py<y+h)coverage[yy*s.width+xx]=Math.max(coverage[yy*s.width+xx],96+(ch.codePointAt(0)%16)*6)}}if(['copy','source-in','source-out','destination-in','destination-atop'].includes(run.composite)){left=0;top=0;right=s.width;bottom=s.height}for(let y=top;y<bottom;y++)for(let x=left;x<right;x++){if(!clipContains(run.clips,x+.5,y+.5))continue;compositePixel(p,(y*s.width+x)*4,paintColor(run.paint,x+.5,y+.5),run.alpha*coverage[y*s.width+x]/255,run.composite,s.opaque)}}};
  const multiply=(a,b)=>[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]];
  /* shared_canvas_paths */
  const fillRectangle=(c,x,y,w,h,clear)=>{const a=[x,y,w,h].map(Number);if(!a.every(Number.isFinite)||!a[2]||!a[3])return;queuePath(c,rectanglePath(c,...a),'nonzero',false,clear)};
  class CanvasRenderingContext2D {
    constructor(key,s,attributes={}){if(key!==token)throw new TypeError('Illegal constructor');contexts.set(this,{surface:s,draw:defaults(),stack:[],attributes:{alpha:attributes.alpha!==false,colorSpace:attributes.colorSpace||'srgb',colorType:'unorm8',desynchronized:!!attributes.desynchronized,willReadFrequently:!!attributes.willReadFrequently}});s.opaque=attributes.alpha===false;s.onResize=()=>{const c=contexts.get(this);c.draw=defaults();c.stack=[];c.path=[]}}
    get canvas(){return contextState(this).surface.canvas}getContextAttributes(){return {...contextState(this).attributes}}isContextLost(){contextState(this);return false}
    save(){const c=contextState(this);c.stack.push({...c.draw,transform:c.draw.transform.slice(),dash:c.draw.dash.slice()})}restore(){const c=contextState(this);if(c.stack.length)c.draw=c.stack.pop()}reset(){const c=contextState(this);resize(c.surface,c.surface.width,c.surface.height)}
    getTransform(){const a=contextState(this).draw.transform;return typeof DOMMatrix==='function'?new DOMMatrix(a):{a:a[0],b:a[1],c:a[2],d:a[3],e:a[4],f:a[5]}}resetTransform(){contextState(this).draw.transform=[1,0,0,1,0,0]}setTransform(...args){const c=contextState(this);if(!args.length){this.resetTransform();return}let a=args;if(args.length===1){const o=args[0]||{};a=[o.a??o.m11??1,o.b??o.m12??0,o.c??o.m21??0,o.d??o.m22??1,o.e??o.m41??0,o.f??o.m42??0]}a=a.map(Number);if(a.length===6&&a.every(Number.isFinite))c.draw.transform=a}transform(...a){a=a.map(Number);if(a.length===6&&a.every(Number.isFinite)){const c=contextState(this);c.draw.transform=multiply(c.draw.transform,a)}}translate(x,y){this.transform(1,0,0,1,x,y)}scale(x,y){this.transform(x,0,0,y,0,0)}rotate(angle){angle=Number(angle);this.transform(Math.cos(angle),Math.sin(angle),-Math.sin(angle),Math.cos(angle),0,0)}
    setLineDash(value){const c=contextState(this),a=Array.from(value,Number);if(a.some(v=>!Number.isFinite(v)||v<0))return;c.draw.dash=a.length%2?a.concat(a):a}getLineDash(){return contextState(this).draw.dash.slice()}
    clearRect(x,y,w,h){fillRectangle(contextState(this),x,y,w,h,true)}fillRect(x,y,w,h){fillRectangle(contextState(this),x,y,w,h,false)}
    createImageData(width,height){contextState(this);if(images.has(width))return new ImageData(width.width,width.height);return new ImageData(Math.abs(Number(width)),Math.abs(Number(height)))}
    getImageData(x,y,width,height){const c=contextState(this),s=c.surface;if(s.originClean===false)fail('SecurityError','Canvas is not origin-clean');[x,y,width,height]=[x,y,width,height].map(v=>Math.trunc(Number(v)));if(!width||!height)fail('IndexSizeError','ImageData dimensions must be nonzero');if(width<0){x+=width;width=-width}if(height<0){y+=height;height=-height}const out=new ImageData(width,height),p=buffer(s);for(let yy=0;yy<height;yy++)for(let xx=0;xx<width;xx++){const px=x+xx,py=y+yy;if(px<0||py<0||px>=s.width||py>=s.height)continue;const i=(py*s.width+px)*4,j=(yy*width+xx)*4,a=p[i+3];out.data[j+3]=a;for(let k=0;k<3;k++)out.data[j+k]=a?Math.round(p[i+k]*255/a):0}return out}
    putImageData(image,x,y,...dirty){const c=contextState(this),s=c.surface,d=images.get(image);if(!d)throw new TypeError('Expected ImageData');x=Math.trunc(Number(x));y=Math.trunc(Number(y));if(!Number.isFinite(x)||!Number.isFinite(y))throw new TypeError('Invalid coordinate');let [dx,dy,dw,dh]=dirty.length?dirty.map(Number):[0,0,d.width,d.height];if(dw<0){dx+=dw;dw=-dw}if(dh<0){dy+=dh;dh=-dh}const p=buffer(s);for(let yy=Math.max(0,Math.trunc(dy));yy<Math.min(d.height,dy+dh);yy++)for(let xx=Math.max(0,Math.trunc(dx));xx<Math.min(d.width,dx+dw);xx++){const tx=x+xx,ty=y+yy;if(tx<0||ty<0||tx>=s.width||ty>=s.height)continue;const i=(yy*d.width+xx)*4,j=(ty*s.width+tx)*4,a=d.data[i+3];p[j+3]=s.opaque?255:a;for(let k=0;k<3;k++)p[j+k]=Math.round(d.data[i+k]*a/255)}}
    drawImage(source,...args){const c=contextState(this),destination=c.surface;let image;if(bitmaps.has(source)){image=bitmaps.get(source);if(image.closed)fail('InvalidStateError','ImageBitmap is closed')}else if(canvases.has(source)||typeof HTMLCanvasElement!=='undefined'&&source instanceof HTMLCanvasElement){const ss=sync(state(source));image={width:ss.width,height:ss.height,pixels:buffer(ss).slice(),unmodeled:ss.unmodeled,originClean:ss.originClean}}else if(typeof HTMLImageElement!=='undefined'&&source instanceof HTMLImageElement){image=sourceImage(source);if(!image){if(source.complete)fail('InvalidStateError','Image is broken');return}}else{record(c,'drawImage',args);return}let sx=0,sy=0,sw=image.width,sh=image.height,dx,dy,dw=sw,dh=sh;if(args.length===2)[dx,dy]=args;else if(args.length===4)[dx,dy,dw,dh]=args;else if(args.length===8)[sx,sy,sw,sh,dx,dy,dw,dh]=args;else throw new TypeError('Invalid drawImage arguments');[sx,sy,sw,sh,dx,dy,dw,dh]=[sx,sy,sw,sh,dx,dy,dw,dh].map(Number);if(![sx,sy,sw,sh,dx,dy,dw,dh].every(Number.isFinite)||!sw||!sh||!dw||!dh)return;if(image.originClean===false)destination.originClean=false;const m=c.draw.transform;if(m[1]||m[2]||m[0]<0||m[3]<0||sw<0||sh<0||dw<0||dh<0||(c.draw.globalCompositeOperation!=='source-over'&&c.draw.globalCompositeOperation!=='copy')){record(c,'drawImage',args);return}dx=dx*m[0]+m[4];dy=dy*m[3]+m[5];dw*=m[0];dh*=m[3];const p=buffer(destination),input=image.pixels.slice(),ga=c.draw.globalAlpha;for(let yy=Math.max(0,Math.ceil(dy));yy<Math.min(destination.height,dy+dh);yy++)for(let xx=Math.max(0,Math.ceil(dx));xx<Math.min(destination.width,dx+dw);xx++){if(!clipContains(c.draw.clipPaths,xx+.5,yy+.5))continue;const ix=Math.floor(sx+(xx-dx)*sw/dw),iy=Math.floor(sy+(yy-dy)*sh/dh);if(ix<0||iy<0||ix>=image.width||iy>=image.height)continue;const i=(iy*image.width+ix)*4,j=(yy*destination.width+xx)*4,a=input[i+3]/255*ga,keep=c.draw.globalCompositeOperation==='copy'?0:1-a;for(let k=0;k<3;k++)p[j+k]=Math.round(input[i+k]*ga+p[j+k]*keep);p[j+3]=destination.opaque?255:Math.round(a*255+p[j+3]*keep)}destination.unmodeled||=image.unmodeled}
    createLinearGradient(...args){const c=contextState(this),gradient=new CanvasGradient(token,'linear',args.map(Number));gradients.get(gradient).matrix=c.draw.transform.slice();return gradient}createRadialGradient(...args){const c=contextState(this);if(Number(args[2])<0||Number(args[5])<0)fail('IndexSizeError','Negative radius');const gradient=new CanvasGradient(token,'radial',args.map(Number));gradients.get(gradient).matrix=c.draw.transform.slice();return gradient}
    measureText(text){const c=contextState(this);return new TextMetrics(token,textMetrics(c.draw,String(text)))}
    fillText(text,x,y,maxWidth){queueText(contextState(this),String(text),x,y,maxWidth,false)}strokeText(text,x,y,maxWidth){queueText(contextState(this),String(text),x,y,maxWidth,true)}
  }
  class OffscreenCanvasRenderingContext2D {constructor(key,s,attributes){const context=new CanvasRenderingContext2D(key,s,attributes);Object.setPrototypeOf(context,OffscreenCanvasRenderingContext2D.prototype);return context}}
  for(const key of Object.keys(defaults()).filter(k=>k!=='transform'&&k!=='dash'))Object.defineProperty(CanvasRenderingContext2D.prototype,key,{get(){return contextState(this).draw[key]},set(value){const c=contextState(this);if(key==='font'){value=String(value);if(!/\b(?:[1-9]\d*(?:\.\d+)?|0?\.\d+)px(?:\s|\/)/.test(value))return;c.draw[key]=value;return}if(key==='letterSpacing'||key==='wordSpacing'){value=String(value);if(!/^-?(?:\d+(?:\.\d+)?|\.\d+)px$/.test(value))return;c.draw[key]=value;return}const allowed={textAlign:['start','end','left','right','center'],textBaseline:['top','hanging','middle','alphabetic','ideographic','bottom'],direction:['ltr','rtl','inherit'],lineCap:['butt','round','square'],lineJoin:['round','bevel','miter']};if(allowed[key]&&!allowed[key].includes(String(value)))return;if(key==='fillStyle'||key==='strokeStyle'||key==='shadowColor'){if(gradients.has(value)&&key!=='shadowColor'){c.draw[key]=value;return}const rgba=color(String(value));if(rgba)c.draw[key]=normalizedColor(rgba);return}if(typeof c.draw[key]==='number'){value=Number(value);if(!Number.isFinite(value)||key==='globalAlpha'&&(value<0||value>1)||['lineWidth','miterLimit'].includes(key)&&value<=0||key==='shadowBlur'&&value<0)return}else if(typeof c.draw[key]==='boolean')value=!!value;else value=String(value);c.draw[key]=value},enumerable:true,configurable:true});
  for(const name of ['beginPath','closePath','moveTo','lineTo','bezierCurveTo','quadraticCurveTo','arc','arcTo','ellipse','rect','roundRect','clip','fill','stroke','strokeRect'])Object.defineProperty(CanvasRenderingContext2D.prototype,name,{value:{[name](...args){record(contextState(this),name,args)}}[name],writable:true,enumerable:true,configurable:true});
  installPathObservations(CanvasRenderingContext2D.prototype);
  for(const key of Reflect.ownKeys(CanvasRenderingContext2D.prototype))if(key!=='constructor')Object.defineProperty(OffscreenCanvasRenderingContext2D.prototype,key,Object.getOwnPropertyDescriptor(CanvasRenderingContext2D.prototype,key));
  const getContext=(canvas,kind,attributes)=>{const s=sync(state(canvas));kind=String(kind);const entry=factories.get(kind);if(!entry)return null;if(s.kind)return s.kind===entry.canonical?s.context:null;const context=entry.create(canvas,attributes||{},s);if(context){s.kind=entry.canonical;s.context=context}return context};
  class OffscreenCanvas extends EventTarget {constructor(width,height){super();if(arguments.length<2)throw new TypeError('Two dimensions are required');fresh(this,uint(width),uint(height))}get width(){return state(this).width}set width(value){const s=state(this);resize(s,uint(value),s.height)}get height(){return state(this).height}set height(value){const s=state(this);resize(s,s.width,uint(value))}getContext(kind,attributes){return getContext(this,kind,attributes)}transferToImageBitmap(){const s=state(this);if(!s.kind)fail('InvalidStateError','Canvas has no context');if(!s.width||!s.height)fail('InvalidStateError','Canvas has zero dimensions');const bitmap=new ImageBitmap(token,{width:s.width,height:s.height,pixels:buffer(s).slice(),closed:false,unmodeled:s.unmodeled,originClean:s.originClean});s.pixels=null;s.operations=[];s.pendingText=[];s.unmodeled=false;s.onTransfer?.();return bitmap}}
  factories.set('2d',{canonical:'2d',create:(canvas,attributes,s)=>new (canvas instanceof OffscreenCanvas?OffscreenCanvasRenderingContext2D:CanvasRenderingContext2D)(token,s,attributes)});
  const createImageBitmap=async(source,...args)=>{let b;if(bitmaps.has(source)){const a=bitmaps.get(source);if(a.closed)fail('InvalidStateError','ImageBitmap is closed');b={...a,pixels:a.pixels.slice()}}else if(canvases.has(source)||typeof HTMLCanvasElement!=='undefined'&&source instanceof HTMLCanvasElement){const s=sync(state(source));b={width:s.width,height:s.height,pixels:buffer(s).slice(),closed:false,unmodeled:s.unmodeled,originClean:s.originClean}}else if(typeof HTMLImageElement!=='undefined'&&source instanceof HTMLImageElement){b=sourceImage(source);if(!b)fail('InvalidStateError','Image is not decoded');b.closed=false}else if(images.has(source)){const d=images.get(source),pixels=d.data.slice();for(let i=0;i<pixels.length;i+=4)for(let k=0;k<3;k++)pixels[i+k]=Math.round(pixels[i+k]*pixels[i+3]/255);b={width:d.width,height:d.height,pixels,closed:false}}else fail('NotSupportedError','Decoding this ImageBitmap source is not implemented');if(!b.width||!b.height)fail('InvalidStateError','ImageBitmap source has zero dimensions');let options=args[0]||{};if(args.length>=4){let [x,y,w,h]=args.slice(0,4).map(value=>Math.trunc(Number(value)));if(![x,y,w,h].every(Number.isFinite)||!w||!h)fail('RangeError','Invalid ImageBitmap crop');if(w<0){x+=w;w=-w}if(h<0){y+=h;h=-h}const pixels=storage(w,h);for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){const sx=x+xx,sy=y+yy;if(sx<0||sy<0||sx>=b.width||sy>=b.height)continue;const i=(sy*b.width+sx)*4,j=(yy*w+xx)*4;for(let k=0;k<4;k++)pixels[j+k]=b.pixels[i+k]}b={...b,width:w,height:h,pixels};options=args[4]||{}}else if(args.length>1)throw new TypeError('Invalid ImageBitmap arguments');if(options.resizeWidth!==undefined||options.resizeHeight!==undefined||options.imageOrientation==='flipY'||options.premultiplyAlpha==='none'||options.colorSpaceConversion==='none')fail('NotSupportedError','ImageBitmap conversion options are not implemented');return new ImageBitmap(token,b)};
  for(const [name,ctor] of Object.entries({OffscreenCanvas,CanvasRenderingContext2D,OffscreenCanvasRenderingContext2D,ImageData,ImageBitmap,CanvasGradient,TextMetrics})){if(name==='CanvasRenderingContext2D'&&typeof document==='undefined')continue;Object.defineProperty(ctor.prototype,Symbol.toStringTag,{value:name,configurable:true});Object.defineProperty(globalThis,name,{value:ctor,writable:true,configurable:true})}
  Object.defineProperty(globalThis,'createImageBitmap',{value:createImageBitmap,writable:true,configurable:true});
  if(typeof HTMLCanvasElement==='function'){const p=HTMLCanvasElement.prototype;for(const [key,fallback]of [['width',300],['height',150]])Object.defineProperty(p,key,{get(){return htmlSize(this,key,fallback)},set(value){value=Number(value)>>>0;this.setAttribute(key,String(value));const s=state(this);resize(s,htmlSize(this,'width',300),htmlSize(this,'height',150))},enumerable:true,configurable:true});const setAttribute=p.setAttribute;Object.defineProperty(p,'setAttribute',{value:function(name,value){setAttribute.call(this,name,value);if(/^(width|height)$/i.test(String(name))){const s=state(this);resize(s,htmlSize(this,'width',300),htmlSize(this,'height',150))}},writable:true,configurable:true});Object.defineProperty(p,'getContext',{value:function(kind,attributes){return getContext(this,kind,attributes)},writable:true,enumerable:true,configurable:true})}
  if(typeof markNative==='function'){for(const ctor of [OffscreenCanvas,CanvasRenderingContext2D,OffscreenCanvasRenderingContext2D,ImageData,ImageBitmap,CanvasGradient,TextMetrics]){markNative(ctor,ctor.name);for(const key of Reflect.ownKeys(ctor.prototype)){if(key==='constructor'||typeof key!=='string')continue;const d=Object.getOwnPropertyDescriptor(ctor.prototype,key);if(typeof d.value==='function')markNative(d.value,key);if(d.get)markNative(d.get,key,'get ');if(d.set)markNative(d.set,key,'set ');if(!d.enumerable)Object.defineProperty(ctor.prototype,key,{...d,enumerable:true})}}markNative(createImageBitmap,'createImageBitmap');if(typeof HTMLCanvasElement==='function'){for(const name of ['getContext','setAttribute','width','height']){const d=Object.getOwnPropertyDescriptor(HTMLCanvasElement.prototype,name);if(d?.value)markNative(d.value,name);if(d?.get)markNative(d.get,name,'get ');if(d?.set)markNative(d.set,name,'set ')}}}
  const preserveFunction=(fn,reference)=>{if(typeof fn!=='function'||typeof reference!=='function')return;for(const key of ['length','name'])Object.defineProperty(fn,key,{value:reference[key],configurable:true})};
  for(const name of interfaceNames){const ctor=globalThis[name],reference=reflectedInterfaces.get(name);if(!ctor||!reference)continue;Object.defineProperty(ctor,'length',{value:workerProperties.get(name)?.functionLength??reference.length,configurable:true});for(const key of Object.getOwnPropertyNames(ctor.prototype)){if(key==='constructor')continue;const current=Object.getOwnPropertyDescriptor(ctor.prototype,key),original=reference.members[key];if(!original){if(name!=='HTMLCanvasElement')delete ctor.prototype[key];continue}preserveFunction(current.value,original.value);const member=(selectedWorkerExposure?.prototypes?.[name]||[]).find(p=>p.name===key);if(current.value&&member?.functionName)Object.defineProperty(current.value,'name',{value:member.functionName,configurable:true});if(current.value&&member?.functionLength!==undefined&&member.functionLength!==null)Object.defineProperty(current.value,'length',{value:member.functionLength,configurable:true});preserveFunction(current.get,original.get);preserveFunction(current.set,original.set);if(current.get){Object.defineProperty(current.get,'length',{value:0,configurable:true});Object.defineProperty(current.get,'name',{value:'get '+key,configurable:true})}if(current.set){Object.defineProperty(current.set,'length',{value:1,configurable:true});Object.defineProperty(current.set,'name',{value:'set '+key,configurable:true})}Object.defineProperty(ctor.prototype,key,{...current,enumerable:original.enumerable,configurable:original.configurable,...('writable'in current?{writable:original.writable}:{})})}}
  if(imageBitmapArity!==undefined)Object.defineProperty(createImageBitmap,'length',{value:workerProperties.get('createImageBitmap')?.functionLength??selectedWorkerExposure?.prototypes?.WorkerGlobalScope?.find(p=>p.name==='createImageBitmap')?.functionLength??imageBitmapArity,configurable:true});
  return {registerContext(kind,create,canonical=kind){factories.set(kind,{create,canonical})},state,buffer,bitmapState:bitmap=>bitmaps.get(bitmap)};
})();
