// Canonical realm-independent primitives shared by Window and Worker.
  const textEncoderSlots=new WeakSet();
  const utf8Bytes=input=>{const out=[];for(let i=0;i<input.length;i++){let point=input.charCodeAt(i);if(point>=0xd800&&point<=0xdbff){const next=input.charCodeAt(i+1);if(next>=0xdc00&&next<=0xdfff){point=0x10000+((point-0xd800)<<10)+(next-0xdc00);i++}else point=0xfffd}else if(point>=0xdc00&&point<=0xdfff)point=0xfffd;if(point<=0x7f)out.push(point);else if(point<=0x7ff)out.push(0xc0|(point>>6),0x80|(point&63));else if(point<=0xffff)out.push(0xe0|(point>>12),0x80|((point>>6)&63),0x80|(point&63));else out.push(0xf0|(point>>18),0x80|((point>>12)&63),0x80|((point>>6)&63),0x80|(point&63))}return out};
  class TextEncoder { constructor(){textEncoderSlots.add(this)} get encoding(){if(!textEncoderSlots.has(this))throw new TypeError('Illegal invocation');return'utf-8'} encode(input=''){if(!textEncoderSlots.has(this))throw new TypeError('Illegal invocation');return new Uint8Array(utf8Bytes(String(input)))} encodeInto(source,destination){if(!textEncoderSlots.has(this))throw new TypeError('Illegal invocation');if(!(destination instanceof Uint8Array))throw new TypeError("Failed to execute 'encodeInto' on 'TextEncoder': parameter 2 is not of type 'Uint8Array'.");source=String(source);let read=0,written=0;for(const scalar of source){const bytes=utf8Bytes(scalar);if(written+bytes.length>destination.length)break;destination.set(bytes,written);written+=bytes.length;read+=scalar.length}return{read,written}} }
  Object.defineProperty(TextEncoder.prototype,Symbol.toStringTag,{value:'TextEncoder',configurable:true});
  for(const name of ['encode','encodeInto'])markNative(TextEncoder.prototype[name],name);
  markNative(Object.getOwnPropertyDescriptor(TextEncoder.prototype,'encoding').get,'encoding','get ');
  const domExceptionSlots=new WeakMap();
  const domExceptionString=value=>{if(typeof value==='symbol')throw new TypeError('Cannot convert a Symbol value to a string');return String(value)};
  const domExceptionCodes={IndexSizeError:1,HierarchyRequestError:3,WrongDocumentError:4,InvalidCharacterError:5,NoModificationAllowedError:7,NotFoundError:8,NotSupportedError:9,InUseAttributeError:10,InvalidStateError:11,SyntaxError:12,InvalidModificationError:13,NamespaceError:14,InvalidAccessError:15,TypeMismatchError:17,SecurityError:18,NetworkError:19,AbortError:20,URLMismatchError:21,QuotaExceededError:22,TimeoutError:23,InvalidNodeTypeError:24,DataCloneError:25};
  // DOMException instances inherit Error.prototype, but the interface object
  // inherits Function.prototype. Avoid class extends Error, whose super lookup
  // would also require the incorrect constructor-object inheritance.
  class DOMException {
    constructor(message='',name='Error'){
      message=domExceptionString(message);name=domExceptionString(name);
      const error=Reflect.construct(Error,[],new.target);
      domExceptionSlots.set(error,{message,name});
      // Preserve the engine's Error.isError classification without publishing
      // Error's own stack/message properties on the DOMException instance.
      delete error.stack;
      return error;
    }
    get name(){return domExceptionSlots.get(this).name}
    get message(){return domExceptionSlots.get(this).message}
    get code(){const name=domExceptionSlots.get(this).name;return Object.prototype.hasOwnProperty.call(domExceptionCodes,name)?domExceptionCodes[name]:0}
  }
  Object.setPrototypeOf(DOMException.prototype,Error.prototype);
  const decodeForm=s=>decodeURIComponent(String(s).replace(/\+/g,' '));
  const encodeForm=s=>encodeURIComponent(String(s)).replace(/%20/g,'+').replace(/[!'()~]/g,c=>'%'+c.charCodeAt(0).toString(16).toUpperCase());
  const urlSearchParamsSlots=new WeakMap(),urlSearchParamsState=value=>urlSearchParamsSlots.get(value),readSearchParams=value=>{const state=urlSearchParamsState(value);if(!state.url)return state.pairs;return parseSearchParams(state.url.search)},writeSearchParams=(value,pairs)=>{const state=urlSearchParamsState(value);if(state.url)state.url.search=pairs.length?'?'+pairs.map(x=>encodeForm(x[0])+'='+encodeForm(x[1])).join('&'):'';else state.pairs=pairs},parseSearchParams=input=>{const pairs=[],text=String(input||'').replace(/^\?/,'');if(text)for(const part of text.split('&')){const i=part.indexOf('=');pairs.push([decodeForm(i<0?part:part.slice(0,i)),decodeForm(i<0?'':part.slice(i+1))])}return pairs};
  class URLSearchParams { constructor(init=''){let pairs=[];if(init instanceof URLSearchParams)pairs=readSearchParams(init).map(x=>x.slice());else if(typeof init==='string')pairs=parseSearchParams(init);else if(init&&typeof init[Symbol.iterator]==='function'){for(const pair of init)pairs.push([String(pair[0]),String(pair[1])])}else if(init)for(const key of Object.keys(init))pairs.push([key,String(init[key])]);urlSearchParamsSlots.set(this,{pairs,url:null})} get size(){return readSearchParams(this).length} append(name,value){const p=readSearchParams(this);p.push([String(name),String(value)]);writeSearchParams(this,p)} delete(name,value){name=String(name);const hasValue=arguments.length>1,valueString=String(value);writeSearchParams(this,readSearchParams(this).filter(x=>x[0]!==name||(hasValue&&x[1]!==valueString)))} get(name){name=String(name);return readSearchParams(this).find(x=>x[0]===name)?.[1]??null} getAll(name){name=String(name);return readSearchParams(this).filter(x=>x[0]===name).map(x=>x[1])} has(name,value){name=String(name);const hasValue=arguments.length>1,valueString=String(value);return readSearchParams(this).some(x=>x[0]===name&&(!hasValue||x[1]===valueString))} set(name,value){name=String(name);value=String(value);const p=readSearchParams(this),out=[];let done=false;for(const x of p){if(x[0]===name){if(!done){out.push([name,value]);done=true}}else out.push(x)}if(!done)out.push([name,value]);writeSearchParams(this,out)} sort(){const p=readSearchParams(this).map((x,i)=>[x,i]);p.sort((a,b)=>a[0][0]<b[0][0]?-1:a[0][0]>b[0][0]?1:a[1]-b[1]);writeSearchParams(this,p.map(x=>x[0]))} toString(){return readSearchParams(this).map(x=>encodeForm(x[0])+'='+encodeForm(x[1])).join('&')} entries(){return readSearchParams(this)[Symbol.iterator]()} keys(){return readSearchParams(this).map(x=>x[0])[Symbol.iterator]()} values(){return readSearchParams(this).map(x=>x[1])[Symbol.iterator]()} forEach(callback,thisArg){for(const [name,value] of readSearchParams(this))callback.call(thisArg,value,name,this)} [Symbol.iterator](){return this.entries()} }
  const stringBytes=s=>{const binary=unescape(encodeURIComponent(String(s))),out=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)out[i]=binary.charCodeAt(i);return out};
  const bytesString=bytes=>{let binary='';for(let i=0;i<bytes.length;i++)binary+=String.fromCharCode(bytes[i]);try{return decodeURIComponent(escape(binary))}catch{return'\ufffd'}};
  const blobSlots=new WeakMap(),blobState=value=>blobSlots.get(value),blobBytes=part=>{if(part instanceof Blob)return blobState(part).bytes;if(part instanceof ArrayBuffer)return new Uint8Array(part);if(ArrayBuffer.isView(part))return new Uint8Array(part.buffer,part.byteOffset,part.byteLength);return stringBytes(String(part))};
  class Blob { constructor(parts=[],options={}){if(parts==null||typeof parts[Symbol.iterator]!=='function')throw new TypeError("Failed to construct 'Blob': The provided value cannot be converted to a sequence.");const chunks=[...parts].map(blobBytes),size=chunks.reduce((n,x)=>n+x.byteLength,0),bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}const type=String(options.type||'');blobSlots.set(this,{bytes,type:/^[\x20-\x7e]*$/.test(type)?type.toLowerCase():''})} get size(){return blobState(this).bytes.byteLength} get type(){return blobState(this).type} slice(start=0,end=this.size,contentType=''){const state=blobState(this),size=this.size;start=Number(start);end=Number(end);start=start<0?Math.max(size+start,0):Math.min(start,size);end=end<0?Math.max(size+end,0):Math.min(end,size);return new Blob([end<start?new Uint8Array(0):state.bytes.slice(start,end)],{type:contentType})} arrayBuffer(){return Promise.resolve(blobState(this).bytes.slice().buffer)} bytes(){return Promise.resolve(blobState(this).bytes.slice())} text(){return Promise.resolve(bytesString(blobState(this).bytes))} stream(){const bytes=blobState(this).bytes.slice();return new ReadableStream({start(controller){controller.enqueue(bytes);controller.close()}})} }
  const fileSlots=new WeakMap();
  class File extends Blob { constructor(bits,fileName,options={}){super(bits,options);fileSlots.set(this,{name:String(fileName).replace(/\//g,':'),lastModified:options.lastModified===undefined?Date.now():Number(options.lastModified)})} get name(){return fileSlots.get(this).name} get lastModified(){return fileSlots.get(this).lastModified} get webkitRelativePath(){return''} }
  const blobURLs=new Map();
  const urlSlots=new WeakMap(),urlState=value=>urlSlots.get(value),urlParts=value=>host.urlParts(urlState(value).href),setURLPart=(value,name,part)=>{const state=urlState(value);state.href=host.setURLPart(state.href,name,String(part))};
  class URL { constructor(input,base=undefined){input=String(input);base=base===undefined?'':String(base);let href;try{href=host.urlParts(input,base).href}catch{throw new TypeError('Invalid URL')}urlSlots.set(this,{href,searchParams:null})} get href(){return urlState(this).href} set href(v){urlState(this).href=host.urlParts(String(v)).href} get origin(){return urlParts(this).origin} get protocol(){return urlParts(this).protocol} set protocol(v){setURLPart(this,'protocol',v)} get username(){return urlParts(this).username} set username(v){setURLPart(this,'username',v)} get password(){return urlParts(this).password} set password(v){setURLPart(this,'password',v)} get host(){return urlParts(this).host} set host(v){setURLPart(this,'host',v)} get hostname(){return urlParts(this).hostname} set hostname(v){setURLPart(this,'hostname',v)} get port(){return urlParts(this).port} set port(v){setURLPart(this,'port',v)} get pathname(){return urlParts(this).pathname} set pathname(v){setURLPart(this,'pathname',v)} get search(){return urlParts(this).search} set search(v){setURLPart(this,'search',v)} get searchParams(){const state=urlState(this);if(!state.searchParams){state.searchParams=new URLSearchParams();urlSearchParamsState(state.searchParams).url=this}return state.searchParams} get hash(){return urlParts(this).hash} set hash(v){setURLPart(this,'hash',v)} toString(){return this.href} toJSON(){return this.href} static canParse(input,base){try{new URL(input,base);return true}catch{return false}} static parse(input,base){try{return new URL(input,base)}catch{return null}} static createObjectURL(object){if(!(object instanceof Blob))throw new TypeError("Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.");const value=host.createObjectURL(Array.from(blobState(object).bytes),object.type);blobURLs.set(value,object);return value} static revokeObjectURL(value){value=String(value);blobURLs.delete(value);host.revokeObjectURL(value)} }
  const headersSlots=new WeakMap();
  // WebIDL checks the receiver and required arguments before any user conversion.
  const headersState=(receiver,count=0,required=0)=>{const state=headersSlots.get(receiver);if(!state)throw new TypeError('Illegal invocation');if(count<required)throw new TypeError('Not enough arguments');return state};
  const headerName=value=>{const name=String(value).trim().toLowerCase();if(!name||/[^!#$%&'*+.^_`|~0-9a-z-]/.test(name))throw new TypeError('Invalid header name');return name},headerValue=value=>{const text=String(value).trim();if(/[\0\r\n]/.test(text))throw new TypeError('Invalid header value');return text};
  class Headers { constructor(init){const values=new Map();headersSlots.set(this,values);if(init instanceof Headers)for(const [name,value] of init)this.append(name,value);else if(init&&typeof init[Symbol.iterator]==='function')for(const pair of init)this.append(pair[0],pair[1]);else if(init)for(const name of Object.keys(init))this.append(name,init[name])} append(name,value){const values=headersState(this,arguments.length,2),key=headerName(name),next=headerValue(value);values.set(key,values.has(key)?values.get(key)+', '+next:next)} delete(name){headersState(this,arguments.length,1).delete(headerName(name))} get(name){return headersState(this,arguments.length,1).get(headerName(name))??null} has(name){return headersState(this,arguments.length,1).has(headerName(name))} set(name,value){headersState(this,arguments.length,2).set(headerName(name),headerValue(value))} entries(){const state=headersState(this);return(function*(){for(const entry of [...state].sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0))yield entry})()} keys(){headersState(this);return Array.from(this.entries(),entry=>entry[0])[Symbol.iterator]()} values(){headersState(this);return Array.from(this.entries(),entry=>entry[1])[Symbol.iterator]()} forEach(callback,thisArg){headersState(this,arguments.length,1);if(typeof callback!=='function')throw new TypeError('Callback must be callable');for(const [name,value] of this)callback.call(thisArg,value,name,this)} [Symbol.iterator](){return this.entries()} }
  Object.defineProperty(Headers.prototype,Symbol.toStringTag,{value:'Headers',configurable:true});
