package nativebuild

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// Ensure builds the native style/layout archive when it is absent or stale.
// It returns the repository root containing the runtime command.
func Ensure() (string, error) {
	root, err := repositoryRoot()
	if err != nil {
		return "", err
	}
	target, archiveName, err := platformTarget()
	if err != nil {
		return "", err
	}
	nativeDir := filepath.Join(root, "internal", "layoutblitz", "native")
	archive := filepath.Join(nativeDir, "target", target, "release", archiveName)
	marker := filepath.Join(nativeDir, "target", target, "release", ".mimic-source-sha256")
	digest, err := sourceDigest(root)
	if err != nil {
		return "", err
	}
	if data, readErr := os.ReadFile(marker); readErr == nil && strings.TrimSpace(string(data)) == digest {
		if _, statErr := os.Stat(archive); statErr == nil {
			return root, ensureArchiveStamp(root, archive)
		}
	}
	fmt.Fprintln(os.Stderr, "Mimic: native style/layout inputs changed; building them once...")
	if rustup, lookErr := exec.LookPath("rustup"); lookErr == nil {
		cmd := exec.Command(rustup, "target", "add", target)
		cmd.Dir, cmd.Stdout, cmd.Stderr = root, os.Stdout, os.Stderr
		if err := cmd.Run(); err != nil {
			return "", fmt.Errorf("install Rust target %s: %w", target, err)
		}
	}
	cargo, err := exec.LookPath("cargo")
	if err != nil {
		return "", fmt.Errorf("native style/layout build requires Cargo in PATH: %w", err)
	}
	cmd := exec.Command(cargo, "build", "--manifest-path", filepath.Join(nativeDir, "Cargo.toml"), "--target", target, "--target-dir", filepath.Join(nativeDir, "target"), "--release", "--locked")
	cmd.Dir, cmd.Stdout, cmd.Stderr = root, os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("build native style/layout archive: %w", err)
	}
	if err := os.WriteFile(marker, []byte(digest+"\n"), 0o644); err != nil {
		return "", fmt.Errorf("write native build marker: %w", err)
	}
	return root, ensureArchiveStamp(root, archive)
}

func sourceDigest(root string) (string, error) {
	roots := []string{filepath.Join(root, "internal", "layoutblitz", "native"), filepath.Join(root, "internal", "layouttaffy", "native")}
	var files []string
	for _, tree := range roots {
		err := filepath.WalkDir(tree, func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() && entry.Name() == "target" {
				return filepath.SkipDir
			}
			if !entry.IsDir() {
				files = append(files, path)
			}
			return nil
		})
		if err != nil {
			return "", err
		}
	}
	sort.Strings(files)
	h := sha256.New()
	for _, path := range files {
		rel, _ := filepath.Rel(root, path)
		_, _ = io.WriteString(h, filepath.ToSlash(rel)+"\x00")
		data, err := os.ReadFile(path)
		if err != nil {
			return "", err
		}
		_, _ = h.Write(data)
		_, _ = h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

func ensureArchiveStamp(root, archive string) error {
	data, err := os.ReadFile(archive)
	if err != nil {
		return fmt.Errorf("read native archive: %w", err)
	}
	digest := sha256.Sum256(data)
	content := fmt.Sprintf("/* Generated by Mimic's native build; do not edit. */\n#define MIMIC_BLITZ_NATIVE_ARCHIVE_SHA256 \"%x\"\n", digest)
	path := filepath.Join(root, "internal", "layoutblitz", "native_build_stamp.h")
	if old, err := os.ReadFile(path); err == nil && string(old) == content {
		return nil
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func repositoryRoot() (string, error) {
	_, source, _, _ := runtime.Caller(0)
	wd, _ := os.Getwd()
	for _, start := range []string{filepath.Dir(source), wd} {
		for dir := start; dir != filepath.Dir(dir); dir = filepath.Dir(dir) {
			if data, err := os.ReadFile(filepath.Join(dir, "go.mod")); err == nil && strings.Contains(string(data), "module github.com/moreveal/mimic") {
				return dir, nil
			}
		}
	}
	return "", fmt.Errorf("cannot locate Mimic repository (go.mod)")
}

func platformTarget() (string, string, error) {
	if runtime.GOARCH != "amd64" {
		return "", "", fmt.Errorf("native style/layout is not validated on %s", runtime.GOARCH)
	}
	switch runtime.GOOS {
	case "windows":
		return "x86_64-pc-windows-gnu", "libmimic_layout_blitz.a", nil
	case "linux":
		return "x86_64-unknown-linux-gnu", "libmimic_layout_blitz.a", nil
	default:
		return "", "", fmt.Errorf("native style/layout is not supported on %s", runtime.GOOS)
	}
}
