[package]
name = "mimic-layout-blitz"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
mimic-taffy-layout = { path = "../../layouttaffy/native" }
blitz-dom = { git = "https://github.com/moreveal/blitz.git", rev = "19a72d4a4163038d748603fbcf709d38bfa6a998", default-features = false, features = ["system-fonts"] }
style = { package = "stylo", version = "0.21" }
style_dom = { package = "stylo_dom", version = "0.21" }
blitz-traits = { git = "https://github.com/moreveal/blitz.git", rev = "19a72d4a4163038d748603fbcf709d38bfa6a998" }
markup5ever = "0.39"

[patch.crates-io]
parley = { path = "vendor/parley" }
