[package]
name = "mimic-layout-blitz"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
mimic-taffy-layout = { path = "../../layouttaffy/native" }
blitz-dom = { path = "vendor/blitz-dom", default-features = false, features = ["system-fonts"] }
style = { package = "stylo", version = "0.21" }
style_dom = { package = "stylo_dom", version = "0.21" }
blitz-traits = { git = "https://github.com/DioxusLabs/blitz.git", rev = "e7bf7bca452bc9194ac5c9bcf2ac3c0ebcf02e09" }
markup5ever = "0.39"
