<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>mimic_blazor_probe</RootNamespace>
    <AssemblyName>mimic_blazor_probe</AssemblyName>
  </PropertyGroup>
</Project>
