#!/usr/bin/env python3
"""Build the shared Blitz and legacy Taffy migration archive."""

from __future__ import annotations

import platform
import hashlib
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "internal" / "layoutblitz" / "native" / "Cargo.toml"


def stamp_archive(archive: Path) -> None:
    """Make the external Rust archive an explicit cgo package cache input.

    Go does not hash libraries named in LDFLAGS. A Rust-only change could
    otherwise return a previously linked executable from Go's build cache.
    Headers in the cgo package directory are included in its action hash.
    """
    digest = hashlib.sha256()
    with archive.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    stamp = ROOT / "internal" / "layoutblitz" / "native_build_stamp.h"
    content = (
        "/* Generated by tools/build_native_layout.py; do not edit. */\n"
        f'#define MIMIC_BLITZ_NATIVE_ARCHIVE_SHA256 "{digest.hexdigest()}"\n'
    )
    if not stamp.exists() or stamp.read_text(encoding="utf-8") != content:
        stamp.write_text(content, encoding="utf-8")


def main() -> None:
    machine = platform.machine().lower()
    if machine not in {"amd64", "x86_64"}:
        raise SystemExit(f"native layout is not validated on {machine}")
    target = (
        "x86_64-pc-windows-gnu"
        if platform.system() == "Windows"
        else "x86_64-unknown-linux-gnu"
    )
    if platform.system() not in {"Windows", "Linux"}:
        raise SystemExit(f"native layout is not supported on {platform.system()}")
    rustup = shutil.which("rustup")
    if rustup:
        subprocess.run([rustup, "target", "add", target], check=True, cwd=ROOT)
    subprocess.run(
        [
            "cargo",
            "build",
            "--manifest-path",
            str(MANIFEST),
            "--target",
            target,
            "--target-dir",
            str(MANIFEST.parent / "target"),
            "--release",
            "--locked",
        ],
        check=True,
        cwd=ROOT,
    )
    stamp_archive(MANIFEST.parent / "target" / target / "release" / "libmimic_layout_blitz.a")


if __name__ == "__main__":
    main()
