#!/usr/bin/env python3
"""Generate all CDP wire types, validation descriptors and an honest inventory.

Inputs are retained exact-Chrome schema + provenance and a small implementation
manifest. This command, including --check, is entirely offline. A separate
capture_cdp_protocol.py command explicitly refreshes the upstream schema.
"""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import re
import subprocess


ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path("internal/cdp/protocol/chrome152.json")
SUPPORT = Path("internal/cdp/protocol_support.json")
PRIMITIVES = {"string", "integer", "number", "boolean", "object", "array", "any", "binary"}
SUPPORT_STATUSES = {"unsupported", "partial", "implemented"}
HEADER = "// Code generated by tools/generate_cdp.py from pinned Chrome 152; DO NOT EDIT.\npackage cdp\n\n"


def go_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def name(value: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", value):
        raise ValueError(f"not a protocol identifier: {value!r}")
    return value[0].upper() + value[1:]


def qualified(domain: str, ref: str) -> str:
    return ref if "." in ref else domain + "." + ref


def go_ref(domain: str, ref: str) -> str:
    return "".join(name(part) for part in qualified(domain, ref).split("."))


def read_source(root: Path = ROOT) -> tuple[dict, dict]:
    raw = (root / SOURCE).read_bytes()
    source = json.loads(raw)
    provenance = json.loads((root / SOURCE.with_suffix(".source.json")).read_text(encoding="utf-8"))
    target = json.loads((root / "chrome/152/target.json").read_text(encoding="utf-8"))
    if hashlib.sha256(raw).hexdigest() != provenance.get("sha256"):
        raise ValueError("CDP source hash mismatch; refresh explicitly or restore the retained input")
    if provenance.get("sourcePath") != SOURCE.as_posix():
        raise ValueError("CDP source path mismatch")
    metadata = provenance["captureMetadata"]
    for key, expected in {
        "chromeVersion": target["chrome_version"],
        "chromiumCommit": target["chromium_commit"],
        "chromiumRevision": target["main_branch_revision"],
        "v8Version": target["differential_browser"]["v8_version"],
        "platform": target["platform"],
    }.items():
        if metadata.get(key) != expected:
            raise ValueError(f"CDP source provenance mismatch: {key}")
    if source.get("version") != {"major": "1", "minor": "3"}:
        raise ValueError("unexpected CDP wire protocol version")
    return source, provenance


def validate_schema(source: dict) -> dict[str, dict]:
    """Fail closed on unknown schema syntax, missing references and collisions."""
    types = {}
    seen_members = set()
    seen_domains = set()
    go_names = {"CDPInteger"}

    def remember_go(symbol: str):
        if symbol in go_names:
            raise ValueError(f"generated Go identifier collision: {symbol}")
        go_names.add(symbol)

    for domain in source["domains"]:
        dn = domain["domain"]
        if dn in seen_domains:
            raise ValueError(f"duplicate domain: {dn}")
        seen_domains.add(dn)
        for row in domain.get("types", []):
            key = qualified(dn, row["id"])
            if key in types:
                raise ValueError(f"duplicate type: {key}")
            types[key] = row
            remember_go(go_ref(dn, row["id"]))
        for category in ("commands", "events"):
            for row in domain.get(category, []):
                key = (category, dn + "." + row["name"])
                if key in seen_members:
                    raise ValueError(f"duplicate member: {key}")
                seen_members.add(key)
                prefix = name(dn) + name(row["name"])
                for suffix in (("Params", "Result") if category == "commands" else ("Event",)):
                    remember_go(prefix + suffix)

    def fields(dn: str, values: list):
        seen = set()
        for row in values:
            if row["name"] in seen:
                raise ValueError(f"duplicate field in {dn}: {row['name']}")
            seen.add(row["name"])
            field(dn, row)

    def field(dn: str, row: dict):
        if "$ref" in row:
            if "type" in row or qualified(dn, row["$ref"]) not in types:
                raise ValueError(f"unresolved or mixed reference: {dn} {row}")
        elif row.get("type") not in PRIMITIVES:
            raise ValueError(f"unknown wire type: {dn} {row}")
        if row.get("type") == "array":
            if "items" not in row:
                raise ValueError(f"array without items: {dn} {row}")
            field(dn, row["items"])
        if "properties" in row:
            if row.get("type") != "object":
                raise ValueError(f"properties on non-object: {dn} {row}")
            fields(dn, row["properties"])

    for domain in source["domains"]:
        dn = domain["domain"]
        for row in domain.get("types", []):
            field(dn, row)
        for category in ("commands", "events"):
            for row in domain.get(category, []):
                fields(dn, row.get("parameters", []))
                fields(dn, row.get("returns", []))

    # References through object/array fields may recurse; pure alias cycles may not.
    for key in types:
        visited = set()
        current = key
        while "$ref" in types[current]:
            if current in visited:
                raise ValueError(f"type alias cycle: {key}")
            visited.add(current)
            current = qualified(current.split(".")[0], types[current]["$ref"])
    return types


def descriptor(domain: str, row: dict) -> str:
    if "$ref" in row:
        return "{ref:" + go_string(qualified(domain, row["$ref"])) + "}"
    kind = row["type"]
    result = "{kind: protocol" + name(kind)
    if kind == "array":
        result += ", items: &protocolType" + descriptor(domain, row["items"])
    if "properties" in row:
        result += ", properties:" + descriptors(domain, row["properties"])
    return result + "}"


def descriptors(domain: str, rows: list) -> str:
    return "[]protocolField{" + ",".join(
        "{name:" + go_string(row["name"]) + ", optional:" + str(bool(row.get("optional"))).lower()
        + ", value:protocolType" + descriptor(domain, row) + "}"
        for row in rows
    ) + "}"


def registry_go(source: dict) -> str:
    chunks = [HEADER, "var protocolTypes = map[string]protocolType{\n"]
    for domain in sorted(source["domains"], key=lambda d: d["domain"]):
        dn = domain["domain"]
        for row in sorted(domain.get("types", []), key=lambda t: t["id"]):
            chunks.append(go_string(qualified(dn, row["id"])) + ":" + descriptor(dn, row) + ",\n")
    chunks.append("}\n\n")
    for category, symbol in (("commands", "protocolCommands"), ("events", "protocolEvents")):
        chunks.append("var " + symbol + " = map[string]protocolCommand{\n")
        for domain in sorted(source["domains"], key=lambda d: d["domain"]):
            dn = domain["domain"]
            for row in sorted(domain.get(category, []), key=lambda c: c["name"]):
                chunks.append(go_string(dn + "." + row["name"]) + ":{parameters:" + descriptors(dn, row.get("parameters", []))
                              + ", returns:" + descriptors(dn, row.get("returns", [])) + "},\n")
        chunks.append("}\n\n")
    return "".join(chunks)


def field_type(domain: str, row: dict, *, optional: bool = True) -> str:
    if "$ref" in row:
        result = go_ref(domain, row["$ref"])
    else:
        kind = row["type"]
        result = {
            "string": "string", "binary": "string", "integer": "CDPInteger", "number": "float64",
            "boolean": "bool", "any": "json.RawMessage", "object": "map[string]json.RawMessage",
        }.get(kind)
        if kind == "array":
            result = "[]" + field_type(domain, row["items"], optional=False)
        elif kind == "object" and "properties" in row:
            result = struct_type(domain, row["properties"])
    if optional and row.get("optional") and row.get("type") != "any":
        result = "*" + result
    return result


def struct_type(domain: str, rows: list) -> str:
    parts = ["struct {\n"]
    for row in rows:
        for line in row.get("description", "").splitlines():
            parts.append("// " + line + "\n")
        tag = row["name"] + (",omitempty" if row.get("optional") else "")
        parts.append(name(row["name"]) + " " + field_type(domain, row) + " `json:" + go_string(tag) + "`\n")
    return "".join(parts) + "}"


def types_go(source: dict) -> str:
    chunks = [HEADER, 'import "encoding/json"\n\n',
              "// Optional fields use pointers to preserve omission versus zero values.\n",
              "// RawMessage preserves explicit null and arbitrary Runtime values. Validate\n",
              "// raw command parameters before decoding; Go pointers alone accept null.\n\n"]
    for domain in sorted(source["domains"], key=lambda d: d["domain"]):
        dn = domain["domain"]
        for row in sorted(domain.get("types", []), key=lambda t: t["id"]):
            symbol = go_ref(dn, row["id"])
            chunks.append("// " + symbol + " is the CDP wire type " + qualified(dn, row["id"]) + ".\n")
            chunks.append("type " + symbol + " " + field_type(dn, row, optional=False) + "\n\n")
            if row.get("type") == "integer":
                chunks.append("func (value *" + symbol + ") UnmarshalJSON(raw []byte) error { return (*CDPInteger)(value).UnmarshalJSON(raw) }\n\n")
            for value in row.get("enum", []):
                # Values remain in the authoritative JSON; generated constants are
                # intentionally unnecessary for reliable parameter validation.
                if not isinstance(value, str):
                    raise ValueError(f"non-string protocol enum: {symbol}")
        for category in ("commands", "events"):
            for row in sorted(domain.get(category, []), key=lambda c: c["name"]):
                prefix = name(dn) + name(row["name"])
                roles = (("Params", "parameters"), ("Result", "returns")) if category == "commands" else (("Event", "parameters"),)
                for suffix, key in roles:
                    chunks.append("// " + prefix + suffix + " is the wire " + key + " of " + dn + "." + row["name"] + ".\n")
                    chunks.append("type " + prefix + suffix + " " + struct_type(dn, row.get(key, [])) + "\n\n")
    return "".join(chunks)


def inventory(source: dict, provenance: dict, support: dict) -> dict:
    rows = []
    seen = set()
    for domain in source["domains"]:
        dn = domain["domain"]
        for category, kind in (("commands", "method"), ("events", "event")):
            for item in domain.get(category, []):
                key = dn + "." + item["name"]
                seen.add(key)
                implementation = support.get(key, {"status": "unsupported"})
                if implementation.get("status") not in SUPPORT_STATUSES:
                    raise ValueError(f"invalid support status: {key}")
                if set(implementation) - {"status", "notes", "tests"}:
                    raise ValueError(f"unknown support manifest fields: {key}")
                if "notes" in implementation and not isinstance(implementation["notes"], str):
                    raise ValueError(f"support notes must be a string: {key}")
                if "tests" in implementation and (not isinstance(implementation["tests"], list)
                                                   or not all(isinstance(t, str) for t in implementation["tests"])):
                    raise ValueError(f"support tests must be a string list: {key}")
                if implementation["status"] != "unsupported" and not implementation.get("notes", "").strip():
                    raise ValueError(f"supported behavior requires scope/limitations: {key}")
                if implementation["status"] == "implemented" and not implementation.get("tests"):
                    raise ValueError(f"implemented behavior requires regression evidence: {key}")
                rows.append({
                    "name": key, "kind": kind,
                    "experimental": bool(domain.get("experimental") or item.get("experimental")),
                    "deprecated": bool(domain.get("deprecated") or item.get("deprecated")),
                    "wireSchemaGenerated": True,
                    "requiredParameters": [r["name"] for r in item.get("parameters", []) if not r.get("optional")],
                    "optionalParameters": [r["name"] for r in item.get("parameters", []) if r.get("optional")],
                    "returns": [r["name"] for r in item.get("returns", [])],
                    "support": implementation,
                })
    if set(support) - seen:
        raise ValueError(f"support manifest names absent from pinned CDP: {sorted(set(support)-seen)}")
    rows.sort(key=lambda r: (r["name"], r["kind"]))
    return {
        "schemaVersion": 1,
        "chromeVersion": provenance["captureMetadata"]["chromeVersion"],
        "protocolVersion": source["version"],
        "sourceSHA256": provenance["sha256"],
        "definitions": {
            "wireSchemaGenerated": "Parameter/result shapes exist; this does not imply implemented browser semantics.",
            "unsupported": "No supported behavior is declared. A known schema never implies command success.",
            "partial": "A handler implements documented behavior with remaining semantic limitations.",
            "implemented": "The manifest declares implemented behavior; tests are evidence, not a claim of complete Chrome equivalence.",
        },
        "summary": {
            "domains": len(source["domains"]), "types": sum(len(d.get("types", [])) for d in source["domains"]),
            "methods": dict(sorted(Counter(row["support"]["status"] for row in rows if row["kind"] == "method").items())),
            "events": dict(sorted(Counter(row["support"]["status"] for row in rows if row["kind"] == "event").items())),
        },
        "entries": rows,
    }


def coverage_markdown(output: dict) -> str:
    summary = output["summary"]
    lines = ["<!-- Generated by tools/generate_cdp.py; edit protocol_support.json. -->",
             "# Generated CDP coverage", "",
             "Source: pinned Chrome " + output["chromeVersion"] + ". "
             f"The schema contains {summary['domains']} domains, {sum(summary['methods'].values())} commands, "
             f"{sum(summary['events'].values())} events and {summary['types']} named types. "
             "Wire types and parameter validation do not imply semantic support.", "",
             "`implemented` declares the described command scope with regression evidence; "
             "`partial` records remaining limits; `unsupported` makes no semantic claim. "
             "Evidence links identify tests, not an assertion that every Chrome option is covered. "
             "See [compatibility scope](cdp-compatibility.md) and the "
             "[complete JSON inventory](../internal/cdp/protocol_inventory_generated.json).", "",
             "| Domain | Commands: implemented / partial / unsupported | Events: implemented / partial / unsupported |",
             "|---|---:|---:|"]
    domains = sorted({row["name"].split(".", 1)[0] for row in output["entries"]})
    for domain in domains:
        cells = []
        for kind in ("method", "event"):
            counts = Counter(row["support"]["status"] for row in output["entries"]
                             if row["kind"] == kind and row["name"].startswith(domain + "."))
            cells.append(" / ".join(str(counts[status]) for status in ("implemented", "partial", "unsupported")))
        lines.append("| " + domain + " | " + " | ".join(cells) + " |")
    for kind, title in (("method", "Commands with explicit scope"), ("event", "Events with explicit scope")):
        lines += ["", "## " + title, "", "Unlisted entries are unsupported. Some harmless client acknowledgments "
                  "are explicitly listed as unsupported because they provide no underlying browser behavior.", "",
                  "| Name | Status | Scope and limitations | Regression evidence |", "|---|---|---|---|"]
        for row in output["entries"]:
            support = row["support"]
            if row["kind"] != kind or not support.get("notes"):
                continue
            links = []
            for test in support.get("tests", []):
                path, _, label = test.partition("#")
                links.append("[" + (label or path).replace("|", "\\|") + "](../" + path + ")")
            lines.append("| `" + row["name"] + "` | " + support["status"] + " | "
                         + support["notes"].replace("|", "\\|").replace("\n", " ") + " | "
                         + ("; ".join(links) or "No focused evidence recorded") + " |")
    return "\n".join(lines) + "\n"


def projections(source: dict, provenance: dict, support: dict) -> dict[Path, bytes]:
    validate_schema(source)
    generated = {}
    for filename, content in (("protocol_registry_generated.go", registry_go(source)),
                              ("protocol_types_generated.go", types_go(source))):
        generated[Path("internal/cdp") / filename] = subprocess.run(
            ["gofmt"], input=content.encode("utf-8"), check=True, capture_output=True).stdout
    output = inventory(source, provenance, support)
    generated[Path("internal/cdp/protocol_inventory_generated.json")] = (
        json.dumps(output, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    generated[Path("docs/cdp-coverage-generated.md")] = coverage_markdown(output).encode("utf-8")
    return generated


def generate(root: Path = ROOT, *, check: bool = False):
    source, provenance = read_source(root)
    manifest_path = root / SUPPORT
    support = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else {}
    expected = projections(source, provenance, support)
    for path, raw in expected.items():
        target = root / path
        if check:
            if not target.exists() or target.read_bytes() != raw:
                raise ValueError(f"CDP generated artifact drift: {path.as_posix()}; run python tools/generate_cdp.py")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(raw)
    counts = inventory(source, provenance, support)["summary"]
    action = "PASS: deterministic offline CDP projections" if check else "Generated CDP wire types, validation registry and inventory"
    print(f"{action}: {counts['domains']} domains, {sum(counts['methods'].values())} commands, {sum(counts['events'].values())} events, {counts['types']} types")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare every generated byte and pinned source hash without writes/network")
    args = parser.parse_args()
    generate(check=args.check)
